/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'xs': '0px',
      'sm': '640px',
      'md': '768px',
      'lg': '992px',
      'xl': '1200px',
      '2xl': '1536px',
      'mobile': { 'max': '767px' },
      'tablet': { 'min': '768px', 'max': '991px' },
      'desktop': { 'min': '992px' },
      'portrait': { 'raw': '(orientation: portrait)' },
      'landscape': { 'raw': '(orientation: landscape)' },
      'touch': { 'raw': '(pointer: coarse)' },
      'mouse': { 'raw': '(pointer: fine)' },
    },
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      colors: {
        'brand-primary': 'rgb(var(--color-brand-primary) / <alpha-value>)',
        'brand-secondary': 'rgb(var(--color-brand-secondary) / <alpha-value>)',
        'brand-accent': 'rgb(var(--color-brand-accent) / <alpha-value>)',
        'brand-background': 'rgb(var(--color-brand-background) / <alpha-value>)',
        'brand-surface': 'rgb(var(--color-brand-surface) / <alpha-value>)',
        'brand-text-primary': 'rgb(var(--color-brand-text-primary) / <alpha-value>)',
        'brand-text-secondary': 'rgb(var(--color-brand-text-secondary) / <alpha-value>)',
        'brand-border': 'rgb(var(--color-brand-border) / <alpha-value>)',
        'sidebar': {
          'bg': 'rgb(var(--sidebar-bg) / <alpha-value>)',
          'text': 'rgb(var(--sidebar-text) / <alpha-value>)',
        },
        'tech': {
          'primary': '#6366f1',
          'secondary': '#06b6d4',
          'accent': '#ec4899',
          'dark': '#0f172a',
          'surface': '#1e293b',
        },
      },
      spacing: {
        '0.75': '0.1875rem',
        '1.25': '0.3125rem',
        '1.75': '0.4375rem',
        '2.25': '0.5625rem',
        '2.75': '0.6875rem',
        '3.25': '0.8125rem',
        '3.75': '0.9375rem',
        '4.5': '1.125rem',
        '5.5': '1.375rem',
        '7': '1.75rem',
        '9': '2.25rem',
        '11': '2.75rem',
        '13': '3.25rem',
        '15': '3.75rem',
        '18': '4.5rem',
        '22': '5.5rem',
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      minHeight: {
        'touch-sm': '32px',
        'touch': '36px',
        'touch-md': '40px',
        'touch-lg': '48px',
      },
      minWidth: {
        'touch-sm': '32px',
        'touch': '36px',
        'touch-md': '40px',
        'touch-lg': '48px',
      },
      maxWidth: {
        'sidebar': '14rem',
        'sidebar-sm': '12rem',
      },
      borderRadius: {
        'xs': '0.125rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        'glow-sm': '0 0 10px rgba(var(--color-brand-primary) / 0.3)',
        'glow': '0 0 20px rgba(var(--color-brand-primary) / 0.4)',
        'glow-lg': '0 0 30px rgba(var(--color-brand-primary) / 0.5)',
        'tech-sm': '0 0 10px rgba(99, 102, 241, 0.3)',
        'tech': '0 0 20px rgba(99, 102, 241, 0.5)',
        'tech-lg': '0 0 40px rgba(99, 102, 241, 0.6)',
        'inner-lg': 'inset 0 4px 6px -1px rgb(0 0 0 / 0.1)',
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'fade-in-up': { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-down': { '0%': { opacity: '0', transform: 'translateY(-10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-left': { '0%': { opacity: '0', transform: 'translateX(-20px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        'slide-in-right': { '0%': { opacity: '0', transform: 'translateX(20px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        'slide-in-up': { '0%': { opacity: '0', transform: 'translateY(100%)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'zoom-in': { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'zoom-in-95': { '0%': { opacity: '0', transform: 'scale(.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'bounce-in': { '0%': { opacity: '0', transform: 'scale(0.3)' }, '50%': { transform: 'scale(1.05)' }, '70%': { transform: 'scale(0.9)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'neon-pulse': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(99, 102, 241, 0.5), 0 0 10px rgba(99, 102, 241, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.8), 0 0 30px rgba(99, 102, 241, 0.5)' },
        },
        'gradient-flow': { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      animation: {
        'in': 'fade-in 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.3s ease-out',
        'fade-in-down': 'fade-in-down 0.3s ease-out',
        'slide-in-left': 'slide-in-left 0.3s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-in-up': 'slide-in-up 0.3s ease-out',
        'zoom-in': 'zoom-in 0.2s ease-out',
        'zoom-in-95': 'zoom-in-95 0.3s ease-out',
        'bounce-in': 'bounce-in 0.5s ease-out',
        'neon-pulse': 'neon-pulse 2s ease-in-out infinite',
        'gradient-flow': 'gradient-flow 3s ease infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'tech-gradient': 'linear-gradient(135deg, rgba(99, 102, 241, 0.8) 0%, rgba(6, 182, 212, 0.8) 50%, rgba(236, 72, 153, 0.8) 100%)',
        'shimmer': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.1) 50%, transparent 100%)',
      },
      backgroundSize: {
        '200%': '200% 200%',
        '400%': '400% 400%',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '400': '400ms',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
    },
  },
  plugins: [],
}
