"""Backend quote ORM models."""
from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, Index, Integer, Numeric, String, Text, Uuid
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON

from app.db.session import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class QuoteRecord(Base):
    """One persisted project quote generated by the backend."""

    __tablename__ = "quote_records"
    __table_args__ = (
        Index("ix_quote_records_project_created", "project_id", "created_at"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    user_id: Mapped[str] = mapped_column(String(120), index=True)
    project_id: Mapped[str] = mapped_column(String(160), nullable=False, index=True)
    workflow_id: Mapped[UUID] = mapped_column(
        Uuid,
        ForeignKey("workflow_instances.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    status: Mapped[str] = mapped_column(String(64), default="draft", index=True)
    pricing_source: Mapped[str] = mapped_column(String(120))
    currency: Mapped[str] = mapped_column(String(16), default="CNY")
    quantity: Mapped[int] = mapped_column(Integer)
    material_cost: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    process_cost: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    labor_cost: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    loss_rate: Mapped[Decimal] = mapped_column(Numeric(8, 4))
    overhead_rate: Mapped[Decimal] = mapped_column(Numeric(8, 4))
    margin_rate: Mapped[Decimal] = mapped_column(Numeric(8, 4))
    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    final_quote: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    input_snapshot: Mapped[dict[str, object]] = mapped_column(
        MutableDict.as_mutable(JSON),
        default=dict,
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        onupdate=utcnow,
    )

    line_items: Mapped[list["QuoteLineItem"]] = relationship(
        back_populates="quote",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="QuoteLineItem.id",
    )


class QuoteLineItem(Base):
    """One material/process/labor line in a backend quote."""

    __tablename__ = "quote_line_items"
    __table_args__ = (
        Index("ix_quote_line_items_project_quote", "project_id", "quote_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    quote_id: Mapped[UUID] = mapped_column(
        Uuid,
        ForeignKey("quote_records.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    user_id: Mapped[str] = mapped_column(String(120), index=True)
    project_id: Mapped[str] = mapped_column(String(160), nullable=False, index=True)
    workflow_id: Mapped[UUID] = mapped_column(Uuid, nullable=False, index=True)
    category: Mapped[str] = mapped_column(String(64))
    name: Mapped[str] = mapped_column(String(160))
    unit: Mapped[str] = mapped_column(String(32))
    quantity: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    unit_price: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    total_price: Mapped[Decimal] = mapped_column(Numeric(14, 2))
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    item_metadata: Mapped[dict[str, object]] = mapped_column(
        MutableDict.as_mutable(JSON),
        default=dict,
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    quote: Mapped[QuoteRecord] = relationship(back_populates="line_items")
