from __future__ import annotations

import json
from collections.abc import Iterator
from datetime import datetime, timezone
from pathlib import Path
from uuid import UUID

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, MetaData, create_engine, inspect, select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session
from sqlalchemy.pool import StaticPool

from app.config.settings import settings
from app.db.session import Base
from app.models.persistence import (
    Asset,
    AssetBlobChunk,
    UserSession,
    WorkflowTask,
    WorkflowTaskEvent,
    WorkspaceState,
)


@pytest.fixture
def engine() -> Iterator[Engine]:
    test_engine = create_engine(
        "sqlite+pysqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )

    Base.metadata.create_all(test_engine)
    try:
        yield test_engine
    finally:
        Base.metadata.drop_all(test_engine)
        test_engine.dispose()


def test_all_persistence_models_are_registered_in_shared_metadata() -> None:
    expected_tables = {
        "user_sessions",
        "sso_authorization_states",
        "workspace_states",
        "workflow_tasks",
        "workflow_task_events",
        "assets",
        "asset_blob_chunks",
        "cocreation_project_histories",
        "cocreation_project_version_histories",
    }

    assert expected_tables <= set(Base.metadata.tables)
    assert "request_ip_hash" in Base.metadata.tables["sso_authorization_states"].c
    asset_indexes = {
        index.name: tuple(column.name for column in index.columns)
        for index in Base.metadata.tables["assets"].indexes
    }
    assert asset_indexes["ix_assets_user_created_id"] == (
        "user_id",
        "created_at",
        "id",
    )
    assert "ix_assets_user_id" not in asset_indexes


def test_only_one_workspace_state_is_allowed_per_user(engine: Engine) -> None:
    with Session(engine) as session:
        session.add_all(
            [
                WorkspaceState(user_id="user-1"),
                WorkspaceState(user_id="user-1"),
            ]
        )

        with pytest.raises(IntegrityError):
            session.commit()

        session.rollback()
        valid_workspace = WorkspaceState(user_id="user-2")
        session.add(valid_workspace)
        session.commit()
        valid_workspace_id = valid_workspace.id

    with Session(engine) as verification_session:
        assert verification_session.get(WorkspaceState, valid_workspace_id) is not None


def test_asset_chunk_index_is_unique_within_asset(engine: Engine) -> None:
    with Session(engine) as session:
        asset = Asset(
            user_id="user-1",
            kind="cad",
            filename="model.step",
            content_type="application/step",
            size_bytes=6,
            sha256="a" * 64,
            chunk_size=3,
            chunk_count=2,
            status="ready",
            source="upload",
        )
        asset.chunks.extend(
            [
                AssetBlobChunk(
                    chunk_index=0,
                    size_bytes=3,
                    sha256="b" * 64,
                    content=b"abc",
                ),
                AssetBlobChunk(
                    chunk_index=0,
                    size_bytes=3,
                    sha256="c" * 64,
                    content=b"def",
                ),
            ]
        )
        session.add(asset)

        with pytest.raises(IntegrityError):
            session.commit()

        session.rollback()
        valid_asset = Asset(
            user_id="user-2",
            kind="cad",
            filename="valid.step",
            content_type="application/step",
            size_bytes=3,
            sha256="d" * 64,
            chunk_size=3,
            chunk_count=1,
            status="ready",
            source="upload",
            chunks=[
                AssetBlobChunk(
                    chunk_index=0,
                    size_bytes=3,
                    sha256="e" * 64,
                    content=b"ghi",
                )
            ],
        )
        session.add(valid_asset)
        session.commit()
        valid_asset_id = valid_asset.id

    with Session(engine) as verification_session:
        persisted_asset = verification_session.get(Asset, valid_asset_id)
        assert persisted_asset is not None
        assert len(persisted_asset.chunks) == 1


def test_task_event_sequence_is_unique_within_task(engine: Engine) -> None:
    with Session(engine) as session:
        task = WorkflowTask(
            id="industrial_design_20260723",
            user_id="user-1",
            status="queued",
            progress=0,
            current_step="created",
        )
        task.events.extend(
            [
                WorkflowTaskEvent(
                    sequence=1,
                    event_type="status",
                    status="queued",
                    progress=0,
                    message="created",
                ),
                WorkflowTaskEvent(
                    sequence=1,
                    event_type="status",
                    status="running",
                    progress=10,
                    message="started",
                ),
            ]
        )
        session.add(task)

        with pytest.raises(IntegrityError):
            session.commit()

        session.rollback()
        valid_task = WorkflowTask(
            id="industrial_design_valid",
            user_id="user-2",
            status="queued",
            progress=0,
            current_step="created",
            events=[
                WorkflowTaskEvent(
                    sequence=1,
                    event_type="status",
                    status="queued",
                    progress=0,
                    message="created",
                )
            ],
        )
        session.add(valid_task)
        session.commit()

    with Session(engine) as verification_session:
        persisted_task = verification_session.get(WorkflowTask, "industrial_design_valid")
        assert persisted_task is not None
        assert len(persisted_task.events) == 1


def test_sqlite_engine_connections_enable_foreign_keys(engine: Engine) -> None:
    with engine.connect() as connection:
        assert connection.scalar(text("PRAGMA foreign_keys")) == 1


def test_deleting_asset_cascades_to_blob_chunks(engine: Engine) -> None:
    with Session(engine) as session:
        asset = Asset(
            user_id="user-1",
            kind="cad",
            filename="model.step",
            content_type="application/step",
            size_bytes=3,
            sha256="a" * 64,
            chunk_size=3,
            chunk_count=1,
            status="ready",
            source="upload",
            chunks=[
                AssetBlobChunk(
                    chunk_index=0,
                    size_bytes=3,
                    sha256="b" * 64,
                    content=b"abc",
                )
            ],
        )
        session.add(asset)
        session.commit()
        chunk_id = asset.chunks[0].id

        session.delete(asset)
        session.commit()

        assert session.scalar(
            select(AssetBlobChunk).where(AssetBlobChunk.id == chunk_id)
        ) is None


def test_workspace_asset_reference_is_enforced_and_set_null_on_delete(
    engine: Engine,
) -> None:
    with Session(engine) as session:
        workspace = WorkspaceState(
            user_id="user-invalid-reference",
            selected_reference_asset_id=UUID("00000000-0000-0000-0000-000000000001"),
        )
        session.add(workspace)

        with pytest.raises(IntegrityError):
            session.commit()

        session.rollback()
        asset = Asset(
            user_id="user-1",
            kind="cad",
            filename="reference.step",
            content_type="application/step",
            size_bytes=3,
            sha256="f" * 64,
            chunk_size=3,
            chunk_count=1,
            status="ready",
            source="upload",
        )
        session.add(asset)
        session.flush()
        workspace = WorkspaceState(
            user_id="user-valid-reference",
            selected_reference_asset_id=asset.id,
        )
        session.add(workspace)
        session.commit()
        workspace_id = workspace.id

        session.delete(asset)
        session.commit()

    with Session(engine) as verification_session:
        persisted_workspace = verification_session.get(WorkspaceState, workspace_id)
        assert persisted_workspace is not None
        assert persisted_workspace.selected_reference_asset_id is None


def test_json_defaults_are_not_shared_and_top_level_mutations_persist(
    engine: Engine,
) -> None:
    with Session(engine) as session:
        first = WorkflowTask(
            id="industrial_design_first",
            user_id="user-1",
            status="queued",
            progress=0,
            current_step="created",
            events=[
                WorkflowTaskEvent(
                    sequence=1,
                    event_type="status",
                    status="queued",
                    progress=0,
                    message="created",
                )
            ],
        )
        second = WorkflowTask(
            id="industrial_design_second",
            user_id="user-1",
            status="queued",
            progress=0,
            current_step="created",
        )
        asset = Asset(
            user_id="user-1",
            task=first,
            kind="cad",
            filename="mutable.step",
            content_type="application/step",
            size_bytes=3,
            sha256="9" * 64,
            chunk_size=3,
            chunk_count=1,
            status="ready",
            source="generated",
        )
        workspace = WorkspaceState(user_id="user-json")
        session.add_all([first, second, asset, workspace])
        session.flush()

        first.input_payload["prompt"] = "bearing housing"
        first.design_spec["material"] = "steel"
        first.outputs["asset_id"] = str(asset.id)
        first.diagnostics.append({"code": "queued"})
        first.events[0].event_data["worker"] = "local"
        asset.asset_metadata["generator"] = "jscad"
        workspace.state_data["panel"] = "workflow"
        session.commit()
        asset_id = asset.id
        workspace_id = workspace.id

    with Session(engine) as verification_session:
        persisted_first = verification_session.get(
            WorkflowTask,
            "industrial_design_first",
        )
        persisted_second = verification_session.get(
            WorkflowTask,
            "industrial_design_second",
        )
        assert persisted_first is not None
        assert persisted_second is not None
        assert persisted_first.input_payload == {"prompt": "bearing housing"}
        assert persisted_first.design_spec == {"material": "steel"}
        assert persisted_first.outputs == {"asset_id": str(asset_id)}
        assert persisted_first.diagnostics == [{"code": "queued"}]
        assert persisted_first.events[0].event_data == {"worker": "local"}
        assert persisted_second.input_payload == {}
        assert persisted_second.diagnostics == []
        persisted_asset = verification_session.get(Asset, asset_id)
        persisted_workspace = verification_session.get(WorkspaceState, workspace_id)
        assert persisted_asset is not None
        assert persisted_workspace is not None
        assert persisted_asset.asset_metadata == {"generator": "jscad"}
        assert persisted_workspace.state_data == {"panel": "workflow"}


def test_user_session_json_default_is_created_per_row(engine: Engine) -> None:
    with Session(engine) as session:
        first = UserSession(
            user_id="user-1",
            token_hash="a" * 64,
            expires_at=datetime.now(timezone.utc),
        )
        second = UserSession(
            user_id="user-2",
            token_hash="b" * 64,
            expires_at=datetime.now(timezone.utc),
        )
        session.add_all([first, second])
        session.flush()

        first.client_metadata["client"] = "desktop"
        session.commit()
        first_id = first.id
        second_id = second.id

    with Session(engine) as verification_session:
        persisted_first = verification_session.get(UserSession, first_id)
        persisted_second = verification_session.get(UserSession, second_id)
        assert persisted_first is not None
        assert persisted_second is not None
        assert persisted_first.client_metadata == {"client": "desktop"}
        assert persisted_second.client_metadata == {}


def test_persistence_indexes_avoid_redundant_fk_indexes() -> None:
    event_indexes = {
        tuple(column.name for column in index.columns)
        for index in WorkflowTaskEvent.__table__.indexes
    }
    chunk_indexes = {
        tuple(column.name for column in index.columns)
        for index in AssetBlobChunk.__table__.indexes
    }
    asset_indexes = {
        index.name: tuple(column.name for column in index.columns)
        for index in Asset.__table__.indexes
    }
    workspace_indexes = {
        index.name: tuple(column.name for column in index.columns)
        for index in WorkspaceState.__table__.indexes
    }

    assert ("task_id",) not in event_indexes
    assert ("asset_id",) not in chunk_indexes
    assert ("task_id",) in asset_indexes.values()
    assert workspace_indexes["ix_workspace_states_selected_reference_asset_id"] == (
        "selected_reference_asset_id",
    )


def test_initial_migration_upgrades_and_downgrades_sqlite(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    backend_dir = Path(__file__).resolve().parents[1]
    database_path = tmp_path / "migration.db"
    database_url = f"sqlite+pysqlite:///{database_path}"
    monkeypatch.setattr(settings, "DATABASE_URL", database_url)
    config = Config(backend_dir / "alembic.ini")

    command.upgrade(config, "head")

    migration_engine = create_engine(database_url)
    inspector = inspect(migration_engine)
    assert {
        "user_sessions",
        "sso_authorization_states",
        "workspace_states",
        "workflow_tasks",
        "workflow_task_events",
        "assets",
        "asset_blob_chunks",
    } <= set(inspector.get_table_names())
    assert {
        constraint["name"]
        for constraint in inspector.get_unique_constraints("workflow_task_events")
    } >= {"uq_workflow_task_events_task_sequence"}
    assert {
        constraint["name"]
        for constraint in inspector.get_unique_constraints("asset_blob_chunks")
    } >= {"uq_asset_blob_chunks_asset_chunk"}

    command.check(config)
    command.downgrade(config, "base")

    assert set(inspect(migration_engine).get_table_names()) == {"alembic_version"}
    migration_engine.dispose()


def test_alembic_check_still_detects_unrelated_schema_drift(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    backend_dir = Path(__file__).resolve().parents[1]
    database_url = f"sqlite+pysqlite:///{tmp_path / 'schema-drift.db'}"
    monkeypatch.setattr(settings, "DATABASE_URL", database_url)
    config = Config(backend_dir / "alembic.ini")
    command.upgrade(config, "head")
    migration_engine = create_engine(database_url)
    with migration_engine.begin() as connection:
        connection.execute(
            text("ALTER TABLE assets ADD COLUMN unexpected_drift TEXT")
        )

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(config)

    migration_engine.dispose()


def test_version_asset_reference_migration_preserves_legacy_path_values(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    backend_dir = Path(__file__).resolve().parents[1]
    database_url = f"sqlite+pysqlite:///{tmp_path / 'legacy-paths.db'}"
    monkeypatch.setattr(settings, "DATABASE_URL", database_url)
    config = Config(backend_dir / "alembic.ini")
    command.upgrade(config, "20260723_0001")
    migration_engine = create_engine(database_url)
    now = "2026-07-24 00:00:00+00:00"
    with migration_engine.begin() as connection:
        connection.execute(
            text(
                """
                INSERT INTO cocreation_project_histories (
                    id, user_id, project_id, project_name, created_at, updated_at,
                    project_data
                ) VALUES (
                    1, 'alice', 'legacy-project', 'Legacy Project', :now, :now, '{}'
                )
                """
            ),
            {"now": now},
        )
        connection.execute(
            text(
                """
                INSERT INTO cocreation_project_version_histories (
                    project_history_id, user_id, version_id, label, status, note,
                    is_finalized, generated_image_urls, script_path, work_dir,
                    output_path, created_at, model_objects, parameters,
                    generated_assets, diagnostics, snapshot_data, updated_at
                ) VALUES (
                    1, 'alice', 'v1', 'Legacy', 'completed', 'legacy', 1, '[]',
                    '/legacy/model.js', '/legacy/work', '/legacy/output.step',
                    :now, '[]', '[]', '[]', '[]', '{}', :now
                )
                """
            ),
            {"now": now},
        )

    command.upgrade(config, "head")
    columns = {
        column["name"]
        for column in inspect(migration_engine).get_columns(
            "cocreation_project_version_histories"
        )
    }
    assert {"script_path", "work_dir", "output_path"} <= columns
    assert {"script_asset_id", "output_asset_id"} <= columns
    with migration_engine.connect() as connection:
        upgraded = connection.execute(
            text(
                """
                SELECT script_path, work_dir, output_path
                FROM cocreation_project_version_histories
                WHERE version_id = 'v1'
                """
            )
        ).one()
    assert tuple(upgraded) == (
        "/legacy/model.js",
        "/legacy/work",
        "/legacy/output.step",
    )

    command.downgrade(config, "20260723_0001")
    downgraded_columns = {
        column["name"]
        for column in inspect(migration_engine).get_columns(
            "cocreation_project_version_histories"
        )
    }
    assert {"script_path", "work_dir", "output_path"} <= downgraded_columns
    assert "script_asset_id" not in downgraded_columns
    assert "output_asset_id" not in downgraded_columns
    with migration_engine.connect() as connection:
        downgraded = connection.execute(
            text(
                """
                SELECT script_path, work_dir, output_path
                FROM cocreation_project_version_histories
                WHERE version_id = 'v1'
                """
            )
        ).one()
    assert tuple(downgraded) == tuple(upgraded)
    command.downgrade(config, "base")
    migration_engine.dispose()


def test_0004_migrates_and_reverse_migrates_real_asset_relationship_data(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    backend_dir = Path(__file__).resolve().parents[1]
    database_url = f"sqlite+pysqlite:///{tmp_path / 'v4-roundtrip.db'}"
    monkeypatch.setattr(settings, "DATABASE_URL", database_url)
    config = Config(backend_dir / "alembic.ini")
    command.upgrade(config, "20260726_0003")
    migration_engine = create_engine(database_url)
    metadata = MetaData()
    metadata.reflect(migration_engine)
    projects = metadata.tables["cocreation_project_histories"]
    versions = metadata.tables["cocreation_project_version_histories"]
    assets = metadata.tables["assets"]
    now = datetime(2026, 7, 26, tzinfo=timezone.utc)
    script_id = UUID("10000000-0000-0000-0000-000000000001")
    output_id = UUID("10000000-0000-0000-0000-000000000002")
    generated_id = UUID("10000000-0000-0000-0000-000000000003")
    foreign_id = UUID("10000000-0000-0000-0000-000000000004")

    def asset_row(asset_id: UUID, owner: str) -> dict[str, object]:
        return {
            "id": asset_id.hex,
            "user_id": owner,
            "kind": "cad",
            "filename": f"{asset_id}.step",
            "content_type": "application/step",
            "size_bytes": 1,
            "sha256": "0" * 64,
            "chunk_size": 1,
            "chunk_count": 1,
            "status": "available",
            "source": "legacy",
            "metadata": {},
            "created_at": now,
            "updated_at": now,
        }

    with migration_engine.begin() as connection:
        connection.execute(
            assets.insert(),
            [
                asset_row(script_id, "alice"),
                asset_row(output_id, "alice"),
                asset_row(generated_id, "alice"),
                asset_row(foreign_id, "bob"),
            ],
        )
        connection.execute(
            projects.insert(),
            [
                {
                    "id": 1,
                    "user_id": "alice",
                    "project_id": "roundtrip",
                    "project_name": "Roundtrip",
                    "last_image_url": f"/api/v1/assets/{generated_id}/download",
                    "project_data": {},
                    "created_at": now,
                    "updated_at": now,
                },
                {
                    "id": 2,
                    "user_id": "alice",
                    "project_id": "external-cover",
                    "project_name": "External",
                    "last_image_url": "https://example.com/not-platform.png",
                    "project_data": {},
                    "created_at": now,
                    "updated_at": now,
                },
            ],
        )
        connection.execute(
            versions.insert().values(
                project_history_id=1,
                user_id="alice",
                version_id="roundtrip-v1",
                label="V1",
                status="completed",
                note="legacy",
                is_finalized=False,
                script_asset_id=script_id.hex,
                output_asset_id=output_id.hex,
                generated_image_urls=[],
                generated_assets=[
                    {"assetId": str(generated_id), "kind": "image"},
                    {"assetId": str(generated_id), "kind": "image"},
                    {"assetId": str(foreign_id), "kind": "foreign"},
                    {"assetId": "not-a-uuid", "kind": "invalid"},
                ],
                model_objects=[],
                parameters=[],
                diagnostics=[],
                snapshot_data={},
                created_at=now,
                updated_at=now,
            )
        )

    command.upgrade(config, "20260726_0004")
    with migration_engine.connect() as connection:
        entries = connection.execute(
            text(
                """
                SELECT asset_id, role, kind
                FROM cocreation_version_asset_entries
                ORDER BY role, asset_id
                """
            )
        ).all()
        covers = connection.execute(
            text(
                """
                SELECT project_id, last_image_asset_id
                FROM cocreation_project_histories
                ORDER BY project_id
                """
            )
        ).all()
    assert {(UUID(str(asset_id)), role, kind) for asset_id, role, kind in entries} == {
        (script_id, "script", "script"),
        (output_id, "output", "output"),
        (generated_id, "generated", "image"),
    }
    assert dict(covers)["roundtrip"] is not None
    assert dict(covers)["external-cover"] is None

    with migration_engine.begin() as connection:
        connection.execute(
            text(
                """
                UPDATE cocreation_project_version_histories
                SET script_asset_id = NULL,
                    output_asset_id = NULL,
                    generated_assets = '[]'
                WHERE version_id = 'roundtrip-v1'
                """
            )
        )
        connection.execute(
            text(
                """
                UPDATE cocreation_project_histories
                SET last_image_url = NULL
                WHERE project_id = 'roundtrip'
                """
            )
        )

    command.downgrade(config, "20260726_0003")
    with migration_engine.connect() as connection:
        restored = connection.execute(
            text(
                """
                SELECT script_asset_id, output_asset_id, generated_assets
                FROM cocreation_project_version_histories
                WHERE version_id = 'roundtrip-v1'
                """
            )
        ).one()
        restored_cover = connection.execute(
            text(
                """
                SELECT last_image_url
                FROM cocreation_project_histories
                WHERE project_id = 'roundtrip'
                """
            )
        ).scalar_one()
    assert UUID(str(restored.script_asset_id)) == script_id
    assert UUID(str(restored.output_asset_id)) == output_id
    restored_generated = json.loads(restored.generated_assets)
    assert restored_generated == [
        {"assetId": str(generated_id), "kind": "image"}
    ]
    assert restored_cover == f"/api/v1/assets/{generated_id}/download"
    migration_engine.dispose()


def test_0004_downgrade_does_not_restore_deleted_asset_references(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    backend_dir = Path(__file__).resolve().parents[1]
    database_url = f"sqlite+pysqlite:///{tmp_path / 'v4-deleted-asset.db'}"
    monkeypatch.setattr(settings, "DATABASE_URL", database_url)
    config = Config(backend_dir / "alembic.ini")
    command.upgrade(config, "20260726_0003")
    migration_engine = create_engine(database_url)
    metadata = MetaData()
    metadata.reflect(migration_engine)
    projects = metadata.tables["cocreation_project_histories"]
    versions = metadata.tables["cocreation_project_version_histories"]
    assets = metadata.tables["assets"]
    now = datetime(2026, 7, 26, tzinfo=timezone.utc)
    asset_id = UUID("20000000-0000-0000-0000-000000000001")

    with migration_engine.begin() as connection:
        connection.execute(
            assets.insert().values(
                id=asset_id.hex,
                user_id="alice",
                kind="cad",
                filename="deleted.step",
                content_type="application/step",
                size_bytes=1,
                sha256="1" * 64,
                chunk_size=1,
                chunk_count=1,
                status="available",
                source="legacy",
                metadata={},
                created_at=now,
                updated_at=now,
            )
        )
        connection.execute(
            projects.insert().values(
                id=1,
                user_id="alice",
                project_id="deleted-project",
                project_name="Deleted",
                last_image_url=f"/api/v1/assets/{asset_id}/download",
                project_data={},
                created_at=now,
                updated_at=now,
            )
        )
        connection.execute(
            versions.insert().values(
                project_history_id=1,
                user_id="alice",
                version_id="deleted-v1",
                label="V1",
                status="completed",
                note="legacy",
                is_finalized=False,
                script_asset_id=asset_id.hex,
                output_asset_id=asset_id.hex,
                generated_image_urls=[],
                generated_assets=[
                    {"assetId": str(asset_id), "kind": "cad"}
                ],
                model_objects=[],
                parameters=[],
                diagnostics=[],
                snapshot_data={},
                created_at=now,
                updated_at=now,
            )
        )

    command.upgrade(config, "20260726_0004")
    with migration_engine.begin() as connection:
        connection.execute(assets.delete().where(assets.c.id == asset_id))
    command.downgrade(config, "20260726_0003")

    with migration_engine.connect() as connection:
        restored = connection.execute(
            text(
                """
                SELECT script_asset_id, output_asset_id, generated_assets
                FROM cocreation_project_version_histories
                WHERE version_id = 'deleted-v1'
                """
            )
        ).one()
        restored_cover = connection.execute(
            text(
                """
                SELECT last_image_url
                FROM cocreation_project_histories
                WHERE project_id = 'deleted-project'
                """
            )
        ).scalar_one_or_none()
    assert restored.script_asset_id is None
    assert restored.output_asset_id is None
    assert json.loads(restored.generated_assets) == []
    assert restored_cover is None
    migration_engine.dispose()


def test_0005_backfills_unique_workspace_version_reference_and_reverses(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    backend_dir = Path(__file__).resolve().parents[1]
    database_url = f"sqlite+pysqlite:///{tmp_path / 'v5-reference.db'}"
    monkeypatch.setattr(settings, "DATABASE_URL", database_url)
    config = Config(backend_dir / "alembic.ini")
    command.upgrade(config, "20260726_0004")
    migration_engine = create_engine(database_url)
    metadata = MetaData()
    metadata.reflect(migration_engine)
    projects = metadata.tables["cocreation_project_histories"]
    versions = metadata.tables["cocreation_project_version_histories"]
    workspaces = metadata.tables["workspace_states"]
    now = datetime(2026, 7, 26, tzinfo=timezone.utc)
    workspace_id = UUID("30000000-0000-0000-0000-000000000001")

    with migration_engine.begin() as connection:
        connection.execute(
            projects.insert().values(
                id=1,
                user_id="alice",
                project_id="reference-project",
                project_name="Reference",
                project_data={},
                created_at=now,
                updated_at=now,
            )
        )
        connection.execute(
            versions.insert().values(
                id=1,
                project_history_id=1,
                user_id="alice",
                version_id="reference-v1",
                label="V1",
                status="completed",
                note="legacy",
                is_finalized=False,
                generated_image_urls=[],
                generated_assets=[],
                model_objects=[],
                parameters=[],
                diagnostics=[],
                snapshot_data={},
                created_at=now,
                updated_at=now,
            )
        )
        connection.execute(
            workspaces.insert().values(
                id=workspace_id.hex,
                user_id="alice",
                selected_project_id="reference-project",
                selected_reference_version_id="reference-v1",
                active_scenario="",
                active_workflow_stage="",
                view_mode="",
                scene_mode="",
                selected_industry="",
                generation_prompt="",
                active_step_index=0,
                state_data={},
                version=1,
                created_at=now,
                updated_at=now,
            )
        )

    command.upgrade(config, "20260726_0005")
    with migration_engine.connect() as connection:
        assert connection.execute(
            text(
                """
                SELECT selected_reference_version_history_id
                FROM workspace_states
                WHERE user_id = 'alice'
                """
            )
        ).scalar_one() == 1
    command.downgrade(config, "20260726_0004")
    with migration_engine.connect() as connection:
        assert connection.execute(
            text(
                """
                SELECT selected_reference_version_id
                FROM workspace_states
                WHERE user_id = 'alice'
                """
            )
        ).scalar_one() == "reference-v1"
    migration_engine.dispose()
